# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hand1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 720)
        self.video_window = QtWidgets.QLabel(Form)
        self.video_window.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.video_window.setFont(font)
        self.video_window.setFrameShape(QtWidgets.QFrame.Box)
        self.video_window.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_window.setObjectName("video_window")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1310, 280, 181, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.insert_camera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.insert_camera.setFont(font)
        self.insert_camera.setObjectName("insert_camera")
        self.verticalLayout.addWidget(self.insert_camera)
        self.out_camera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.out_camera.setFont(font)
        self.out_camera.setObjectName("out_camera")
        self.verticalLayout.addWidget(self.out_camera)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1310, 590, 181, 82))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.videonametext = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videonametext.setFont(font)
        self.videonametext.setObjectName("videonametext")
        self.verticalLayout_2.addWidget(self.videonametext)
        self.videoname = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.videoname.setFont(font)
        self.videoname.setObjectName("videoname")
        self.verticalLayout_2.addWidget(self.videoname)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.video_window.setText(_translate("Form", "video"))
        self.insert_camera.setText(_translate("Form", "内置摄像头"))
        self.out_camera.setText(_translate("Form", "外接摄像头"))
        self.videoname.setText(_translate("Form", "确认文件名"))